apps/front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('',views.index,name='index'),
    path('search/',views.search,name='search'),
    path('list/',views.list,name='list'),
]

apps/users/urls.py
from django.urls import path
from .views import my_login,regist,my_logout

app_name = 'auth'

urlpatterns = [
    path('login/',my_login,name='login'),
    path('regist/',regist,name='regist'),
    path('logout/',my_logout,name='logout')
]

zhiwangShow/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/",include('apps.users.urls')),
    path("",include('apps.front.urls'))
]

apps/front/models.py
from django.db import models

# Create your models here.

class Document(models.Model):
    title = models.CharField(max_length=200,default="")
    author = models.CharField(max_length=200,default="")
    author_location = models.TextField(default="")
    acticle_source = models.CharField(max_length=200,default="")
    page_nums = models.CharField(max_length=50,default="")
    summary = models.TextField(default="")

    key_words = models.CharField(max_length=200,default="")
    add_time = models.DateTimeField(auto_now_add=True)

apps/front/views.py
from django.shortcuts import render
from apps.front.models import Document
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.conf import settings


# Create your views here.

def index(request):
    return render(request, 'front/index.html')


def search(request):
    search_cat_id = request.GET.get('searchtype')
    words = request.GET.get('words')
    p = request.GET.get('page', 1)
    if search_cat_id == 'title':
        if words:
            print("123dfsafsda")
            documents = Document.objects.filter(title__contains=words).all()
        else:
            print("11111111")
            documents = Document.objects.all()
    elif search_cat_id == 'author':
        cat = "作者"
        documents = Document.objects.filter(author__contains=words).all()
    elif search_cat_id == 'source':
        cat = "出处"
        documents = Document.objects.filter(acticle_source__contains=words).all()
    elif search_cat_id == 'keywords':
        cat = "关键词"
        documents = Document.objects.filter(key_words__contains=words).all()
    elif search_cat_id == 'summary':
        cat = "摘要"
        documents = Document.objects.filter(summary__contains=words).all()
    else:
        documents = Document.objects.all()
    paginator = Paginator(documents, settings.PERPAGE_DOCUMENT_COUNT)

    num_pages = paginator.num_pages
    left_has_more = False
    right_has_more = False
    # 分页所需参数
    new_context = {}
    try:
        goodses = paginator.page(p)
        current_page = goodses.number
        if current_page <= settings.AROUND_COUNT + 2:
            left_pages = range(1, current_page)
            new_context['left_pages'] = left_pages
        else:
            left_has_more = True
            left_pages = range(current_page - settings.AROUND_COUNT, current_page)
            new_context['left_pages'] = left_pages
            new_context['current_page'] = current_page

        if current_page >= num_pages - 2 - 1:
            right_pages = range(current_page + 1, num_pages + 1)
            new_context['right_pages'] = right_pages
            new_context['current_page'] = current_page
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + settings.AROUND_COUNT + 1)
            new_context['right_pages'] = right_pages
            new_context['current_page'] = current_page

    except PageNotAnInteger:
        documents = paginator.page(1)
    except EmptyPage:
        documents = paginator.page(paginator.num_pages)


    context = {
        'documents': documents,
        'left_has_more':left_has_more,
        'right_has_more':right_has_more,
        'num_pages':num_pages
    }
    context.update(new_context)
    print(context)
    return render(request, 'front/search.html', context=context)



def list(request):
    documents = Document.objects.all()
    p = request.GET.get('page')
    paginator = Paginator(documents, settings.PERPAGE_DOCUMENT_COUNT)
    num_pages = paginator.num_pages
    left_has_more = False
    right_has_more = False
    # 分页所需参数
    new_context = {}
    try:
        goodses = paginator.page(p)
        current_page = goodses.number
        if current_page <= settings.AROUND_COUNT + 2:
            left_pages = range(1, current_page)
            new_context['left_pages'] = left_pages
        else:
            left_has_more = True
            left_pages = range(current_page - settings.AROUND_COUNT, current_page)
            new_context['left_pages'] = left_pages
            new_context['current_page'] = current_page

        if current_page >= num_pages - 2 - 1:
            right_pages = range(current_page + 1, num_pages + 1)
            new_context['right_pages'] = right_pages
            new_context['current_page'] = current_page
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + settings.AROUND_COUNT + 1)
            new_context['right_pages'] = right_pages
            new_context['current_page'] = current_page

    except PageNotAnInteger:
        documents = paginator.page(1)
    except EmptyPage:
        documents = paginator.page(paginator.num_pages)

    context = {
        'documents': documents,
        'left_has_more': left_has_more,
        'right_has_more': right_has_more,
        'num_pages': num_pages
    }
    context.update(new_context)
    print(context)
    return render(request,'front/list.html',context=context)

templates/front/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'js/sweetalert/sweetalert.css' %}" crossorigin="anonymous">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dxajax.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xtalert.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="padding:0 20px" href="/">
                <img src="{% static 'img/logo4.png' %}" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li style="text-align: center"><a href="/">论文文献查询系统</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">可视化</a></li>
                <li><a href="{% url 'front:list' %}">文献列表</a></li>
                <li class="dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                    {% else %}
                        <li><a href="{% url 'auth:login' %}">请登录</a></li>
                    {% endif %}
                <ul class="dropdown-menu">
                    <li><a href="#">个人资料</a></li>
                    <li><a href="#">设置</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth:logout' %}">注销登录</a></li>
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    <div class="title">
        <h2>文献检索系统</h2>
    </div>
    <div class="search-box">
        <div class="row">
            <form action="/search/" method="get">
                <div class="col-md-2">
                    <select name="searchtype" id="search-cat-id">
                        <option value="title">主题</option>
                        <option value="author">作者</option>
                        <option value="source">出处</option>
                        <option value="keywords">关键词</option>
                        <option value="summary">摘要</option>
                    </select>
                </div>
                <div class="col-md-8">
                    <input name="words" type="text" class="form-control" aria-label="">
                </div><!-- /.col-lg-6 -->
                <div class="col-md-1">
                    <input type="submit" class="btn btn-primary" value="搜索">
                </div>
                <div class="col-md-1">
                    <span class="upper-btn btn btn-primary" id="upper-btn">高级搜索</span>
                </div>
            </form>
        </div><!-- /.row -->
    </div>
    <div class="tips">
        <ul>
            <li>关于我们</li>
            <li>版权公告</li>
            <li>在线咨询</li>
            <li>用户建议</li>
        </ul>
    </div>
</div>
</body>
</html>

templates/front/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'js/sweetalert/sweetalert.css' %}" crossorigin="anonymous">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dxajax.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xtalert.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body style="background-color: #d0e9c6">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="padding:0 20px" href="/">
                <img src="{% static 'img/logo4.png' %}" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li style="text-align: center"><a href="/">论文文献查询系统</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">搜索</a></li>
                <li><a href="#">文献列表</a></li>
                <li class="dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                    {% else %}
                        <li><a href="{% url 'auth:login' %}">请登录</a></li>
                    {% endif %}
                <ul class="dropdown-menu">
                    <li><a href="#">个人资料</a></li>
                    <li><a href="#">设置</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth:logout' %}">注销登录</a></li>
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    <div class="search-box">
        <div class="item-group">
            {% for document in documents %}
                <div class="item">
                    <div class="article-title">
                        <h3>{{ document.title }}</h3>
                    </div>
                    <div class="info">
                        <span>作者：{{ document.author }}</span>
                        <span>出处：{{ document.acticle_source }}</span>
                    </div>
                    <div class="summary">
                        <p>{{ document.summary |truncatechars:200 }}</p>
                    </div>
                    <div class="bottom-box">
                        {% if document.key_words != 'nan' %}
                            <span>关键词：{{ document.key_words }}</span>
                        {% else %}
                            <span>关键词：  </span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    {#        <div class="pagination-box">#}
    {#        <nav aria-label="Page navigation">#}
    {#            <ul class="pagination">#}
    {#                <li>#}
    {#                    <a href="#" aria-label="Previous">#}
    {#                        <span aria-hidden="true">&laquo;</span>#}
    {#                    </a>#}
    {#                </li>#}
    {#                <li><a href="#">1</a></li>#}
    {#                <li><a href="#">2</a></li>#}
    {#                <li><a href="#">3</a></li>#}
    {#                <li><a href="#">4</a></li>#}
    {#                <li><a href="#">5</a></li>#}
    {#                <li>#}
    {#                    <a href="#" aria-label="Next">#}
    {#                        <span aria-hidden="true">&raquo;</span>#}
    {#                    </a>#}
    {#                </li>#}
    {#            </ul>#}
    {#        </nav>#}
    {#    </div>#}
    <div class="pagination">
        {#                        上一页#}
        {% if documents.has_previous %}
            <a class="prev page-numbers" href="?page={{ documents.previous_page_number }}">Prev</a>
        {% else %}
            <a class="prev page-numbers disabled" href="javascript:void(0)">Prev</a>
        {% endif %}
        {# 左边页#}
        {% if left_has_more %}
            <a class="page-numbers" href="?page=1">1</a>
            <a class="page-numbers" href="javascript:void(0)">...</a>
        {% endif %}

        {% for left_page in left_pages %}
            <a class="page-numbers" href="?page={{ left_page }}">{{ left_page }}</a>
        {% endfor %}
        {#                            中间页#}
        <a class="page-numbers current" href="?page={{ current_page }}">{{ current_page }}</a>
        {# 右边的页数 #}
        {% for right_page in right_pages %}
            <a class="page-numbers" href="?page={{ right_page }}">{{ right_page }}</a>
        {% endfor %}
        {% if right_has_more %}
            <a class="page-numbers" href="javascript:void(0)">...</a>
            <a class="page-numbers" href="?page={{ num_pages }}">{{ num_pages }}</a>
        {% endif %}

        {#                        下一页#}
        {% if documents.has_next %}
            <a class="next page-numbers"
               href="?page={{ documents.next_page_number }}">Next</a>
        {% else %}
            <a class="next disabled" href="javascript:void(0)">Next</a>
        {% endif %}
    </div>
    <div class="tips">
        <ul>
            <li>关于我们</li>
            <li>版权公告</li>
            <li>在线咨询</li>
            <li>用户建议</li>
        </ul>
    </div>
</div>
</body>
</html>

templates/front/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'js/sweetalert/sweetalert.css' %}" crossorigin="anonymous">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dxajax.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xtalert.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</head>
<body style="background-color: #d0e9c6">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="padding:0 20px" href="/">
                <img src="{% static 'img/logo4.png' %}" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li style="text-align: center"><a href="/">论文文献查询系统</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">搜索</a></li>
                <li><a href="#">文献列表</a></li>
                <li class="dropdown">
                    {% if request.user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                    {% else %}
                        <li><a href="{% url 'auth:login' %}">请登录</a></li>
                    {% endif %}
                <ul class="dropdown-menu">
                    <li><a href="#">个人资料</a></li>
                    <li><a href="#">设置</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'auth:logout' %}">注销登录</a></li>
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="main-container">
    <div class="search-box">
        <div class="item-group">
            {% for document in documents %}
                <div class="item">
                    <div class="article-title">
                        <h3>{{ document.title }}</h3>
                    </div>
                    <div class="info">
                        <span>作者：{{ document.author }}</span>
                        <span>出处：{{ document.acticle_source }}</span>
                    </div>
                    <div class="summary">
                        <p>{{ document.summary |truncatechars:200 }}</p>
                    </div>
                    <div class="bottom-box">
                        {% if document.key_words != 'nan' %}
                            <span>关键词：{{ document.key_words }}</span>
                        {% else %}
                            <span>关键词：  </span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    {% if documents.count > 8 %}
        {#        <div class="pagination-box">#}
        {#        <nav aria-label="Page navigation">#}
        {#            <ul class="pagination">#}
        {#                <li>#}
        {#                    <a href="#" aria-label="Previous">#}
        {#                        <span aria-hidden="true">&laquo;</span>#}
        {#                    </a>#}
        {#                </li>#}
        {#                <li><a href="#">1</a></li>#}
        {#                <li><a href="#">2</a></li>#}
        {#                <li><a href="#">3</a></li>#}
        {#                <li><a href="#">4</a></li>#}
        {#                <li><a href="#">5</a></li>#}
        {#                <li>#}
        {#                    <a href="#" aria-label="Next">#}
        {#                        <span aria-hidden="true">&raquo;</span>#}
        {#                    </a>#}
        {#                </li>#}
        {#            </ul>#}
        {#        </nav>#}
        {#    </div>#}
        <div class="pagination">
            {#                        上一页#}
            {% if documents.has_previous %}
                <a class="prev page-numbers" href="?page={{ documents.previous_page_number }}">Prev</a>
            {% else %}
                <a class="prev page-numbers disabled" href="javascript:void(0)">Prev</a>
            {% endif %}
            {# 左边页#}
            {% if left_has_more %}
                <a class="page-numbers" href="?page=1">1</a>
                <a class="page-numbers" href="javascript:void(0)">...</a>
            {% endif %}

            {% for left_page in left_pages %}
                <a class="page-numbers" href="?page={{ left_page }}">{{ left_page }}</a>
            {% endfor %}
            {#                            中间页#}
            <a class="page-numbers current" href="?page={{ current_page }}">{{ current_page }}</a>
            {# 右边的页数 #}
            {% for right_page in right_pages %}
                <a class="page-numbers" href="?page={{ right_page }}">{{ right_page }}</a>
            {% endfor %}
            {% if right_has_more %}
                <a class="page-numbers" href="javascript:void(0)">...</a>
                <a class="page-numbers" href="?page={{ num_pages }}">{{ num_pages }}</a>
            {% endif %}

            {#                        下一页#}
            {% if documents.has_next %}
                <a class="next page-numbers"
                   href="{% url 'goods:lists' %}?page={{ documents.next_page_number }}">Next</a>
            {% else %}
                <a class="next disabled" href="javascript:void(0)">Next</a>
            {% endif %}
        </div>
    {% endif %}
    <div class="tips">
        <ul>
            <li>关于我们</li>
            <li>版权公告</li>
            <li>在线咨询</li>
            <li>用户建议</li>
        </ul>
    </div>
</div>
</body>
</html>